if UnitClass("player") ~= "Warrior" then return end

SLASH_IDPSWARRIOR1 = "/idps"
function SlashCmdList.IDPSWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:DPSStance("meleeAutoAttack")
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:UseItemConsumableDefensive("Elixir of Poison Resistance", "Naxxramas")
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmorDPSRefresh(4)
	IWin:SweepingStrikes("meleeAutoAttack")
	IWin:SetReservedRageSweepingStrikes("meleeAutoAttack")
	IWin:Whirlwind(IWin_Settings["GCD"], "meleeAutoAttack")
	IWin:SetReservedRageWhirlwind("meleeAutoAttack")
	IWin:UseItemConsumableAOEOffensiveNoGCD(nil, nil, "meleeAutoAttack")
	IWin:UseItemConsumableAOEOffensiveGCD(nil, nil, "meleeAutoAttack")
	IWin:SunderArmorElite()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Execute(IWin_Settings["GCD"], "meleeAutoAttack")
	IWin:SetReservedRageExecute("meleeAutoAttack")
	IWin:HamstringJousting("meleeAutoAttack")
	IWin:Slam()
	IWin:SetReservedRageSlam()
	--IWin:SetSlamQueued()
	IWin:Execute2Hander("meleeAutoAttack")
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:UseItemTrinketOffensiveGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:CastCDLongOffensiveGCD()
	IWin:Whirlwind(nil, 2)
	IWin:SetReservedRageWhirlwindNotEnemyInRange("meleeAutoAttack")
	IWin:Overpower()
	IWin:MasterStrike()
	IWin:SetReservedRageMasterStrike()
	IWin:ConcussionBlow()
	IWin:ThunderClapDPS("meleeAutoAttack")
	IWin:BattleShoutRefresh()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:Rend()
	IWin:SunderArmorDPSRefresh(7)
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:BerserkerRage()
	IWin:HeroicStrike("meleeAutoAttack")
	IWin:SetReservedRageHeroicStrike("meleeAutoAttack")
	IWin:Cleave("meleeAutoAttack")
	IWin:SetReservedRageCleave("meleeAutoAttack")
	IWin:MasterStrikeWindfury()
	IWin:SetReservedRageMasterStrikeWindfury()
	IWin:PummelWindfury()
	IWin:SetReservedRagePummelWindfury()
	IWin:HamstringWindfury()
	IWin:SetReservedRageHamstringWindfury()
	IWin:SunderArmorWindfury()
	IWin:SetReservedRageSunderArmorWindfury()
	IWin:StartAttack()
end

SLASH_IDPSFOCUSWARRIOR1 = "/idpsfocus"
function SlashCmdList.IDPSFOCUSWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:DPSStance(1)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:UseItemConsumableDefensive("Elixir of Poison Resistance", "Naxxramas")
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmorDPSRefresh(4)
	IWin:SunderArmorElite()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Execute(IWin_Settings["GCD"], 1)
	IWin:SetReservedRageExecute(1)
	IWin:HamstringJousting(1)
	IWin:Slam()
	IWin:SetReservedRageSlam()
	--IWin:SetSlamQueued()
	IWin:Execute2Hander(1)
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:UseItemTrinketOffensiveGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:CastCDLongOffensiveGCD()
	IWin:Whirlwind(IWin_Settings["GCD"], 2)
	IWin:SetReservedRageWhirlwind(2)
	IWin:Overpower()
	IWin:MasterStrike()
	IWin:SetReservedRageMasterStrike()
	IWin:ConcussionBlow()
	IWin:BattleShoutRefresh()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:Rend()
	IWin:SunderArmorDPSRefresh(7)
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:BerserkerRage()
	IWin:HeroicStrike(1)
	IWin:SetReservedRageHeroicStrike(1)
	IWin:MasterStrikeWindfury()
	IWin:SetReservedRageMasterStrikeWindfury()
	IWin:PummelWindfury()
	IWin:SetReservedRagePummelWindfury()
	IWin:HamstringWindfury()
	IWin:SetReservedRageHamstringWindfury()
	IWin:SunderArmorWindfury()
	IWin:SetReservedRageSunderArmorWindfury()
	IWin:StartAttack()
end

SLASH_ITANKWARRIOR1 = "/itank"
function SlashCmdList.ITANKWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:CancelSalvation()
	IWin:RevengeReact()
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:ConcussionBlow()
	IWin:ShieldBlock()
	IWin:SlamThreat()
	IWin:SetReservedRageSlamThreat()
	--IWin:SetSlamQueuedThreat()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRage("Bloodthirst", "cooldown")
	IWin:WhirlwindDefensiveTactics(IWin_Settings["GCD"], "meleeAutoAttack")
	IWin:SetReservedRageWhirlwindDefensiveTactics(2)
	IWin:BattleShoutRefresh()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:OverpowerDefensiveTactics()
	IWin:Revenge()
	IWin:SetReservedRageRevenge()
	IWin:UseItemTrinketOffensiveGCD(true)
	IWin:CastCDShortOffensiveGCD(true)
	IWin:SunderArmorFirstStack()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:HeroicStrike(1)
	IWin:StartAttack()
end

SLASH_IHODORWARRIOR1 = "/ihodor"
function SlashCmdList.IHODORWARRIOR()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:RevengeReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:ConcussionBlow()
	IWin:ShieldBlockFRD()
	IWin:UseItemConsumableAOEOffensiveNoGCD(nil, nil, "meleeAutoAttack")
	IWin:UseItemConsumableAOEOffensiveGCD(nil, nil, "meleeAutoAttack")
	IWin:ThunderClap(IWin_Settings["GCD"])
	IWin:WhirlwindDefensiveTactics(IWin_Settings["GCD"], "meleeAutoAttack")
	IWin:SetReservedRageWhirlwindDefensiveTactics(2)
	IWin:SetReservedRage("Thunder Clap", "cooldown")
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:BattleShoutRefresh()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SlamThreat()
	IWin:SetReservedRageSlamThreat()
	--IWin:SetSlamQueuedThreat()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:OverpowerDefensiveTactics()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRage("Bloodthirst", "cooldown")
	IWin:OverpowerDefensiveTactics()
	IWin:Revenge()
	IWin:SetReservedRageRevenge()
	IWin:UseItemTrinketOffensiveGCD(true)
	IWin:CastCDShortOffensiveGCD(true)
	IWin:SunderArmorFirstStack()
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:Cleave(2)
	IWin:StartAttack()
end

SLASH_ICHASEWARRIOR1 = "/ichase"
function SlashCmdList.ICHASEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Charge()
	IWin:Intercept()
	IWin:Intervene()
	IWin:Hamstring()
	IWin:PiercingHowl()
	IWin:StartAttack()
end

SLASH_IKICKWARRIOR1 = "/ikick"
function SlashCmdList.IKICKWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:ShieldBash()
	IWin:Pummel()
	IWin:StartAttack()
end

SLASH_IFEARDANCEWARRIOR1 = "/ifeardance"
function SlashCmdList.IFEARDANCEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:BerserkerRageImmune()
	IWin:StartAttack()
end

SLASH_ITAUNTWARRIOR1 = "/itaunt"
function SlashCmdList.ITAUNTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Taunt()
	IWin:MockingBlow()
	IWin:StartAttack()
end

SLASH_ISHOOTWARRIOR1 = "/ishoot"
function SlashCmdList.ISHOOTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:RangedAttackAny()
	IWin:MarkSkull()
end